# General Workflow Info
name: "stage4-consultant"
type: "typescript"

# Target specific settings for simulation
simulation:
  user-workflow:
    workflow-name: "stage4-consultant"
  workflow-artifacts:
    workflow-path: "./index.ts"
    config-path: "./config.json"
    secrets-path: "../../secrets.yaml"

# Capability requirements (General)
capabilities:
  - "http"
  - "confidentialHttp"
