// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {
    PolicyProtectedUpgradeable
} from "@chainlink/policy-management/core/PolicyProtectedUpgradeable.sol";
import {
    Initializable
} from "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {
    SafeERC20
} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {ECDSA} from "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import {
    MessageHashUtils
} from "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";

interface IComplianceIssuer {
    function isVerified(
        address wallet,
        uint256 minLevel
    ) external view returns (bool);
}

/**
 * @title StealthVaultEscrow (Private Transactions + ACE CCID Edition)
 * @notice Vault contract following Chainlink Confidential Compute guidelines.
 * Acts as an entry point (Shielding) and exit point (Unshielding) with mandatory CCID validation.
 */
contract StealthVaultEscrow is Initializable, PolicyProtectedUpgradeable {
    using SafeERC20 for IERC20;
    using ECDSA for bytes32;

    struct TokenConfig {
        address policyEngine;
        bool isRegistered;
    }

    // Storage
    address public donSigner; // Authorized address of the Chainlink CRE network
    IComplianceIssuer public complianceIssuer; // Phase 1 Identity Contract

    mapping(address => TokenConfig) public registeredTokens;
    mapping(bytes32 => bool) public usedTickets; // Protection against Replay Attacks

    // Events
    event Deposit(address indexed token, address indexed from, uint256 amount);
    event Withdrawal(address indexed token, address indexed to, uint256 amount);
    event TokenRegistered(address indexed token, address indexed policyEngine);

    /// @notice Modifier to ensure the participant has a valid Phase 1 CCID
    modifier onlyVerified(address participant) {
        require(
            complianceIssuer.isVerified(participant, 1),
            "StealthVault: Participant must have a valid CCID (Phase 1 Identity missing)"
        );
        _;
    }

    /// @notice Proxy Initialization
    function initialize(
        address _initialOwner,
        address _policyEngine,
        address _donSigner,
        address _complianceIssuer
    ) public initializer {
        __PolicyProtected_init(_initialOwner, _policyEngine);
        donSigner = _donSigner;
        complianceIssuer = IComplianceIssuer(_complianceIssuer);
    }

    /**
     * @notice Registers a token (RWA or USDC) to be used in the private layer.
     */
    function registerToken(
        address token,
        address policyEngine
    ) external runPolicy {
        registeredTokens[token] = TokenConfig({
            policyEngine: policyEngine,
            isRegistered: true
        });
        emit TokenRegistered(token, policyEngine);
    }

    /**
     * @notice On-Chain entry point (Shielding).
     * Requires the user to have a valid CCID to deposit assets.
     */
    function deposit(
        address token,
        uint256 amount
    ) external onlyVerified(msg.sender) {
        require(
            registeredTokens[token].isRegistered,
            "Vault: Token not registered"
        );
        require(amount > 0, "Vault: Amount must be > 0");

        IERC20(token).safeTransferFrom(msg.sender, address(this), amount);

        emit Deposit(token, msg.sender, amount);
    }

    /**
     * @notice On-Chain exit point (Unshielding).
     * Requires that the claimant has a valid CCID to withdraw assets.
     * @param token Token address to withdraw
     * @param amount Authorized amount
     * @param ticket Cryptographic signature generated by the CRE (TEE)
     */
    function withdrawWithTicket(
        address token,
        uint256 amount,
        bytes calldata ticket
    ) external onlyVerified(msg.sender) {
        require(
            registeredTokens[token].isRegistered,
            "Vault: Token not registered"
        );
        require(amount > 0, "Vault: Amount must be > 0");

        bytes32 ticketHash = keccak256(
            abi.encode(msg.sender, token, amount, address(this))
        );
        bytes32 ethSignedHash = MessageHashUtils.toEthSignedMessageHash(
            ticketHash
        );

        require(!usedTickets[ethSignedHash], "Vault: Ticket already used");

        address signer = ethSignedHash.recover(ticket);
        require(signer == donSigner, "Vault: Invalid TEE signature");

        usedTickets[ethSignedHash] = true;
        IERC20(token).safeTransfer(msg.sender, amount);

        emit Withdrawal(token, msg.sender, amount);
    }

    function updateComplianceIssuer(address _newIssuer) external runPolicy {
        complianceIssuer = IComplianceIssuer(_newIssuer);
    }

    function updateDonSigner(address _newSigner) external runPolicy {
        donSigner = _newSigner;
    }
}
