// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title RegulatoryReportLedger
/// @notice Immutable On-Chain registry of encrypted regulatory reports (Art. 42 Organic Law).
/// @dev This contract stores ONLY hashes and public metadata of the reports.
///      Sensitive data (identity, exact amount) are encrypted off-chain
///      with the regulator's key (SUNAVAL) and are NOT stored on the blockchain.
///
/// Chainlink CRE Alignment:
///   - Risk & Compliance: Immutable registry of regulatory compliance
///   - Privacy: Only public hashes, sensitive data encrypted off-chain
///   - Auditability: Anyone can verify that a report was issued (without seeing content)
///
/// Pattern: Event-Driven Audit Trail
///   - The RegulatoryReportSent event allows indexers and auditors
///     to verify the existence of reports without accessing content.
contract RegulatoryReportLedger {
    /// @notice Authorized address to issue reports (CRE DON / Backend Oracle)
    address public immutable oracleAuthority;

    /// @notice Authorized regulator address (SUNAVAL)
    address public immutable regulatorAddress;

    /// @notice Public structure of a report (without sensitive data)
    struct ReportEntry {
        bytes32 reportHash; // Unique hash of the encrypted report
        address reporter; // Pseudonymous wallet that originated the transaction
        uint256 timestamp; // Time block of issuance
        bytes32 envelopeDigest; // SHA-256 of the encrypted payload (for integrity verification)
    }

    /// @notice List of stored reports
    ReportEntry[] public reports;

    /// @notice Event emitted when registering a new regulatory report
    /// @dev Allows auditors and block explorers to verify compliance
    ///      without accessing sensitive data (Privacy-preserving audit trail)
    event RegulatoryReportSent(
        bytes32 indexed reportHash,
        address indexed regulator,
        address reporter,
        uint256 timestamp
    );

    /// @notice Only the authorized oracle can issue reports
    modifier onlyOracle() {
        require(
            msg.sender == oracleAuthority,
            "RegulatoryReportLedger: Only oracle authority"
        );
        _;
    }

    constructor(address _oracleAuthority, address _regulatorAddress) {
        oracleAuthority = _oracleAuthority;
        regulatorAddress = _regulatorAddress;
    }

    /// @notice Registers a regulatory report on the blockchain
    /// @param reportHash Unique hash of the report (generated by the backend)
    /// @param reporter Pseudonymous wallet of the user who performed the transaction
    /// @param envelopeDigest SHA-256 of the encrypted payload (verifiable integrity)
    function storeReport(
        bytes32 reportHash,
        address reporter,
        bytes32 envelopeDigest
    ) external onlyOracle {
        reports.push(
            ReportEntry({
                reportHash: reportHash,
                reporter: reporter,
                timestamp: block.timestamp,
                envelopeDigest: envelopeDigest
            })
        );

        emit RegulatoryReportSent(
            reportHash,
            regulatorAddress,
            reporter,
            block.timestamp
        );
    }

    /// @notice Returns the total number of issued reports (public audit)
    function totalReports() external view returns (uint256) {
        return reports.length;
    }

    /// @notice Verifies if a report hash exists in the ledger
    function reportExists(bytes32 reportHash) external view returns (bool) {
        for (uint256 i = 0; i < reports.length; i++) {
            if (reports[i].reportHash == reportHash) return true;
        }
        return false;
    }
}
